[core]
databaseFile = "config/database.sqlite3"
siteTitle = "Packet Guardian"
siteCompanyName = ""
registrationPolicyFile = "config/policy.txt"
allowManualRegistrations = true
defaultDeviceLimit = 10

[webserver]
# Leave address blank to bind to all addresses
address = "127.0.0.1"
port = 7000
TLSCertFile = ""
TLSKeyFile = ""
sessionName = "net-guardian"
sessionsDir = "sessions"
# This is the authentication key for web sessions
# Make sure this is unique and protected
sessionsAuthKey = "change me please"
# Optional. Should be 16, 24, or 32 characters long
sessionsEncryptKey = ""

[auth]
# An array of auth types in order of precidence
# Valid values: ldap, local
authMethod = ["local"]
adminUsers = ["admin"]

[auth.ldap]
useAD = true
servers = ["127.0.0.1"]
useTLS = true

# If using Active Directory, ignore the remaining LDAP settings
#useDN = ""
#... other LDAPy things

[dhcp]
configFile = "config/dhcp.conf"
